# Generated by Django 5.0.6 on 2024-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coordinate_application_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
